services:
    # Database
    postgres:
        image: postgres:16
        container_name: postgres
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: "pg_password"
        volumes:
            - ./init-postgres-db.sql:/docker-entrypoint-initdb.d/init-postgres-db.sql
            # - ./postgres_volume/pgdata:/var/lib/postgresql/data

    # RabbitMQ
    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbit
        hostname: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit_user
            - RABBITMQ_DEFAULT_PASS=rabbit_password
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
        #volumes:
        #   - ./rabbitmq:/var/lib/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
